import { useState } from "react";
import { SYNTHETIC_XAI } from "@/data/synthetic";
import { TrendingUp, TrendingDown, Minus } from "lucide-react";
import { cn } from "@/lib/cn";

function formatTime(iso: string) {
  return new Date(iso).toLocaleString();
}

export function ExplainView() {
  const [selectedId, setSelectedId] = useState<string | null>(SYNTHETIC_XAI[0]?.id ?? null);
  const selected = SYNTHETIC_XAI.find((d) => d.id === selectedId) ?? SYNTHETIC_XAI[0];

  return (
    <div className="animate-fade-in flex gap-8">
      <aside className="w-64 shrink-0">
        <p className="text-xs font-semibold uppercase tracking-widest text-cordros-textTertiary mb-3">
          Recent decisions
        </p>
        <ul className="space-y-1">
          {SYNTHETIC_XAI.map((d) => (
            <li key={d.id}>
              <button
                type="button"
                onClick={() => setSelectedId(d.id)}
                className={cn(
                  "w-full rounded-xl px-3 py-2.5 text-left text-sm transition-colors",
                  selectedId === d.id
                    ? "bg-cordros-accentMuted text-cordros-accent"
                    : "text-cordros-textSecondary hover:bg-white/[0.04] hover:text-cordros-text"
                )}
              >
                {d.title}
              </button>
            </li>
          ))}
        </ul>
      </aside>

      <div className="min-w-0 flex-1">
        <header className="mb-6">
          <p className="text-xs font-semibold uppercase tracking-widest text-cordros-textTertiary">
            Explainability (XAI)
          </p>
          <h2 className="mt-2 text-display-sm font-semibold tracking-tight text-cordros-text">
            Why did the model recommend this?
          </h2>
          <div className="mt-3 h-px w-12 bg-cordros-accent" aria-hidden />
          <p className="mt-4 text-sm text-cordros-textSecondary">
            Demo: synthetic explanations. In production, these would be generated by the model orchestration layer.
          </p>
        </header>

        {selected && (
          <div className="rounded-2xl border border-white/[0.06] bg-cordros-surface/80 p-6 space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-cordros-text">{selected.title}</h3>
              <p className="mt-1 text-xs text-cordros-textTertiary">
                Model: {selected.modelVersion} · {formatTime(selected.timestamp)}
              </p>
            </div>
            <div>
              <p className="text-xs font-medium uppercase tracking-wider text-cordros-textTertiary mb-2">Context</p>
              <p className="text-sm text-cordros-textSecondary">{selected.context}</p>
            </div>
            <div>
              <p className="text-xs font-medium uppercase tracking-wider text-cordros-textTertiary mb-2">Outcome</p>
              <p className="text-sm font-medium text-cordros-text">{selected.outcome}</p>
            </div>
            <div>
              <p className="text-xs font-medium uppercase tracking-wider text-cordros-textTertiary mb-3">Factor contribution</p>
              <ul className="space-y-2">
                {selected.factors.map((f) => (
                  <li key={f.name} className="flex items-center gap-3 rounded-lg bg-white/[0.03] px-3 py-2">
                    {f.direction === "positive" && <TrendingUp className="h-4 w-4 text-emerald-500" />}
                    {f.direction === "negative" && <TrendingDown className="h-4 w-4 text-amber-500" />}
                    {f.direction === "neutral" && <Minus className="h-4 w-4 text-cordros-textTertiary" />}
                    <span className="flex-1 text-sm text-cordros-text">{f.name}</span>
                    <span className="font-mono text-xs text-cordros-textSecondary">{f.contribution}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
